export const ISO_BASE = "/assets/office/iso";

/** Pre-rendered Kenney isometric (SE) WebP sprites — 2.5D desk scene. */
export const OFFICE_SPRITES = {
  background: `${ISO_BASE}/room-bg.webp`,
  wallWindow: `${ISO_BASE}/window.webp`,
  desk: `${ISO_BASE}/desk.webp`,
  deskCorner: `${ISO_BASE}/desk-corner.webp`,
  monitor: `${ISO_BASE}/monitor.webp`,
  keyboard: `${ISO_BASE}/keyboard.webp`,
  mouse: `${ISO_BASE}/mouse.webp`,
  lamp: `${ISO_BASE}/lamp.webp`,
  books: `${ISO_BASE}/books.webp`,
  bookcase: `${ISO_BASE}/evidence-board.webp`,
  bookcaseOpen: `${ISO_BASE}/bookcase-open.webp`,
  sideTable: `${ISO_BASE}/side-table.webp`,
  coffee: `${ISO_BASE}/coffee.webp`,
  boxClosed: `${ISO_BASE}/folder.webp`,
  boxOpen: `${ISO_BASE}/folder-open.webp`,
  chair: `${ISO_BASE}/chair.webp`,
  rug: `${ISO_BASE}/rug.webp`,
  coatRack: `${ISO_BASE}/coat-rack.webp`,
  plant: `${ISO_BASE}/plant.webp`,
  phone: `${ISO_BASE}/phone.webp`,
  notebook: `${ISO_BASE}/books.webp`,
  evidenceBoard: `${ISO_BASE}/evidence-board.webp`,
} as const;

export type OfficeSpriteKey = keyof typeof OFFICE_SPRITES;

export type SpritePlacement = {
  id: string;
  sprite: OfficeSpriteKey;
  left: string;
  top: string;
  width: string;
  height?: string;
  layer: "background" | "wall" | "desk" | "props";
  zIndex?: number;
  brightness?: number;
  shadow?: boolean;
  depthBlur?: number;
};

export const DESK_SPRITE_LAYOUT: SpritePlacement[] = [
  {
    id: "room-plate",
    sprite: "background",
    left: "0%",
    top: "0%",
    width: "100%",
    height: "100%",
    layer: "background",
    zIndex: 0,
    brightness: 0.38,
    depthBlur: 1.2,
  },
  {
    id: "window",
    sprite: "wallWindow",
    left: "-2%",
    top: "4%",
    width: "34%",
    layer: "wall",
    zIndex: 2,
    brightness: 0.72,
    shadow: true,
  },
  {
    id: "coat-rack",
    sprite: "coatRack",
    left: "6%",
    top: "34%",
    width: "9%",
    layer: "wall",
    zIndex: 3,
    shadow: true,
  },
  {
    id: "evidence-board-wall",
    sprite: "evidenceBoard",
    left: "68%",
    top: "2%",
    width: "30%",
    layer: "wall",
    zIndex: 4,
    brightness: 0.92,
    shadow: true,
  },
  {
    id: "plant",
    sprite: "plant",
    left: "88%",
    top: "38%",
    width: "9%",
    layer: "wall",
    zIndex: 3,
    shadow: true,
  },
  {
    id: "rug",
    sprite: "rug",
    left: "22%",
    top: "54%",
    width: "52%",
    layer: "desk",
    zIndex: 1,
    brightness: 0.55,
  },
  {
    id: "desk-main",
    sprite: "desk",
    left: "24%",
    top: "46%",
    width: "46%",
    layer: "desk",
    zIndex: 2,
    shadow: true,
  },
  {
    id: "desk-corner",
    sprite: "deskCorner",
    left: "54%",
    top: "44%",
    width: "22%",
    layer: "desk",
    zIndex: 2,
    shadow: true,
  },
  {
    id: "chair",
    sprite: "chair",
    left: "38%",
    top: "58%",
    width: "14%",
    layer: "desk",
    zIndex: 1,
    shadow: true,
  },
  {
    id: "lamp",
    sprite: "lamp",
    left: "18%",
    top: "28%",
    width: "13%",
    layer: "desk",
    zIndex: 5,
    shadow: true,
  },
  {
    id: "monitor",
    sprite: "monitor",
    left: "34%",
    top: "20%",
    width: "24%",
    layer: "desk",
    zIndex: 6,
    shadow: true,
  },
  {
    id: "keyboard",
    sprite: "keyboard",
    left: "36%",
    top: "46%",
    width: "14%",
    layer: "desk",
    zIndex: 7,
    shadow: true,
  },
  {
    id: "mouse",
    sprite: "mouse",
    left: "52%",
    top: "48%",
    width: "5%",
    layer: "desk",
    zIndex: 7,
    shadow: true,
  },
  {
    id: "phone",
    sprite: "phone",
    left: "57%",
    top: "42%",
    width: "10%",
    layer: "desk",
    zIndex: 8,
    shadow: true,
  },
  {
    id: "coffee",
    sprite: "coffee",
    left: "48%",
    top: "50%",
    width: "7%",
    layer: "desk",
    zIndex: 7,
    shadow: true,
  },
  {
    id: "folder-stack",
    sprite: "boxClosed",
    left: "64%",
    top: "40%",
    width: "12%",
    layer: "desk",
    zIndex: 7,
    shadow: true,
  },
  {
    id: "case-archives",
    sprite: "boxOpen",
    left: "72%",
    top: "44%",
    width: "10%",
    layer: "desk",
    zIndex: 6,
    shadow: true,
  },
  {
    id: "notebook",
    sprite: "notebook",
    left: "26%",
    top: "48%",
    width: "8%",
    layer: "desk",
    zIndex: 8,
    shadow: true,
  },
  {
    id: "open-notes",
    sprite: "sideTable",
    left: "28%",
    top: "52%",
    width: "9%",
    layer: "desk",
    zIndex: 6,
    shadow: true,
  },
  {
    id: "books-stack",
    sprite: "books",
    left: "74%",
    top: "52%",
    width: "8%",
    layer: "desk",
    zIndex: 6,
    shadow: true,
  },
];

export const HOTSPOT_LAYOUT = {
  monitor: { left: "34%", top: "20%", width: "24%", height: "34%" },
  phone: { left: "56%", top: "40%", width: "12%", height: "18%" },
  folder: { left: "62%", top: "38%", width: "16%", height: "20%" },
  notebook: { left: "24%", top: "46%", width: "14%", height: "16%" },
  evidenceBoard: { right: "2%", top: "2%", width: "30%", height: "54%" },
} as const;

export const SCENE_LIGHTING = {
  monitorGlow: { left: "34%", top: "22%", width: "24%", height: "28%" },
  lampGlow: { left: "16%", top: "26%", width: "18%", height: "32%" },
  phoneVibrate: { left: "57%", top: "42%", width: "10%", height: "14%" },
} as const;
