export const KENNEY_BASE = "/assets/office/kenney";

export const OFFICE_SPRITES = {
  background: `${KENNEY_BASE}/office-reference.png`,
  wallWindow: `${KENNEY_BASE}/wallWindow.png`,
  wall: `${KENNEY_BASE}/wall.png`,
  desk: `${KENNEY_BASE}/desk.png`,
  deskCorner: `${KENNEY_BASE}/deskCorner.png`,
  monitor: `${KENNEY_BASE}/computerScreen.png`,
  keyboard: `${KENNEY_BASE}/computerKeyboard.png`,
  mouse: `${KENNEY_BASE}/computerMouse.png`,
  lamp: `${KENNEY_BASE}/lampRoundTable.png`,
  books: `${KENNEY_BASE}/books.png`,
  bookcase: `${KENNEY_BASE}/bookcaseClosed.png`,
  bookcaseOpen: `${KENNEY_BASE}/bookcaseOpen.png`,
  sideTable: `${KENNEY_BASE}/sideTableDrawers.png`,
  coffee: `${KENNEY_BASE}/tableCoffee.png`,
  boxClosed: `${KENNEY_BASE}/cardboardBoxClosed.png`,
  boxOpen: `${KENNEY_BASE}/cardboardBoxOpen.png`,
  chair: `${KENNEY_BASE}/chairDesk.png`,
  rug: `${KENNEY_BASE}/rugRectangle.png`,
  coatRack: `${KENNEY_BASE}/coatRackStanding.png`,
  plant: `${KENNEY_BASE}/plantSmall1.png`,
  phone: `${KENNEY_BASE}/televisionModern.png`,
  notebook: `${KENNEY_BASE}/books.png`,
  evidenceBoard: `${KENNEY_BASE}/bookcaseOpen.png`,
} as const;

export type OfficeSpriteKey = keyof typeof OFFICE_SPRITES;

export type SpritePlacement = {
  id: string;
  sprite: OfficeSpriteKey;
  left: string;
  top: string;
  width: string;
  height?: string;
  layer: "background" | "wall" | "desk" | "props";
  zIndex?: number;
  flip?: boolean;
  brightness?: number;
};

export const DESK_SPRITE_LAYOUT: SpritePlacement[] = [
  {
    id: "room-plate",
    sprite: "background",
    left: "0%",
    top: "0%",
    width: "100%",
    height: "100%",
    layer: "background",
    zIndex: 0,
    brightness: 0.42,
  },
  {
    id: "window",
    sprite: "wallWindow",
    left: "3%",
    top: "10%",
    width: "26%",
    layer: "wall",
    zIndex: 2,
  },
  {
    id: "coat-rack",
    sprite: "coatRack",
    left: "8%",
    top: "28%",
    width: "8%",
    layer: "wall",
    zIndex: 3,
  },
  {
    id: "evidence-board-wall",
    sprite: "evidenceBoard",
    left: "72%",
    top: "8%",
    width: "22%",
    layer: "wall",
    zIndex: 3,
  },
  {
    id: "bookcase",
    sprite: "bookcase",
    left: "78%",
    top: "22%",
    width: "14%",
    layer: "wall",
    zIndex: 2,
  },
  {
    id: "rug",
    sprite: "rug",
    left: "28%",
    top: "58%",
    width: "44%",
    layer: "desk",
    zIndex: 1,
  },
  {
    id: "desk-main",
    sprite: "desk",
    left: "30%",
    top: "52%",
    width: "38%",
    layer: "desk",
    zIndex: 2,
  },
  {
    id: "desk-corner",
    sprite: "deskCorner",
    left: "52%",
    top: "50%",
    width: "18%",
    layer: "desk",
    zIndex: 2,
  },
  {
    id: "lamp",
    sprite: "lamp",
    left: "22%",
    top: "38%",
    width: "10%",
    layer: "desk",
    zIndex: 4,
  },
  {
    id: "monitor",
    sprite: "monitor",
    left: "38%",
    top: "36%",
    width: "14%",
    layer: "desk",
    zIndex: 5,
  },
  {
    id: "keyboard",
    sprite: "keyboard",
    left: "40%",
    top: "54%",
    width: "10%",
    layer: "desk",
    zIndex: 6,
  },
  {
    id: "mouse",
    sprite: "mouse",
    left: "52%",
    top: "56%",
    width: "4%",
    layer: "desk",
    zIndex: 6,
  },
  {
    id: "phone",
    sprite: "phone",
    left: "58%",
    top: "54%",
    width: "6%",
    layer: "desk",
    zIndex: 6,
  },
  {
    id: "coffee",
    sprite: "coffee",
    left: "48%",
    top: "58%",
    width: "5%",
    layer: "desk",
    zIndex: 6,
  },
  {
    id: "folder-stack",
    sprite: "boxClosed",
    left: "66%",
    top: "52%",
    width: "8%",
    layer: "desk",
    zIndex: 5,
  },
  {
    id: "case-archives",
    sprite: "boxOpen",
    left: "74%",
    top: "54%",
    width: "9%",
    layer: "desk",
    zIndex: 5,
  },
  {
    id: "notebook",
    sprite: "notebook",
    left: "32%",
    top: "56%",
    width: "6%",
    layer: "desk",
    zIndex: 7,
  },
  {
    id: "open-notes",
    sprite: "sideTable",
    left: "34%",
    top: "58%",
    width: "8%",
    layer: "desk",
    zIndex: 6,
  },
  {
    id: "books-stack",
    sprite: "books",
    left: "70%",
    top: "58%",
    width: "7%",
    layer: "desk",
    zIndex: 6,
  },
  {
    id: "plant",
    sprite: "plant",
    left: "84%",
    top: "42%",
    width: "8%",
    layer: "wall",
    zIndex: 3,
  },
  {
    id: "chair",
    sprite: "chair",
    left: "42%",
    top: "62%",
    width: "12%",
    layer: "desk",
    zIndex: 1,
  },
];

export const HOTSPOT_LAYOUT = {
  monitor: { left: "36%", top: "32%", width: "18%", height: "28%" },
  phone: { left: "56%", top: "50%", width: "10%", height: "14%" },
  folder: { left: "64%", top: "48%", width: "14%", height: "16%" },
  notebook: { left: "30%", top: "52%", width: "12%", height: "14%" },
  evidenceBoard: { right: "6%", top: "8%", width: "22%", height: "48%" },
} as const;
